<?php

namespace App\Filament\Resources\SiteSettings\Schemas;

use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\KeyValue;
use Filament\Forms\Components\Repeater;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Components\Tabs;
use Filament\Schemas\Components\Tabs\Tab;
use Filament\Schemas\Schema;

class SiteSettingForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Tabs::make('Settings')
                    ->tabs([
                        Tab::make('Brand')
                            ->schema([
                                Section::make('Branding')
                                    ->schema([
                                        TextInput::make('site_name')
                                            ->required()
                                            ->maxLength(255),
                                        TextInput::make('tagline')
                                            ->maxLength(255)
                                            ->nullable(),
                                        FileUpload::make('logo_path')
                                            ->image()
                                            ->disk('public')
                                            ->directory('site/branding')
                                            ->maxSize(2048),
                                        FileUpload::make('favicon_path')
                                            ->image()
                                            ->disk('public')
                                            ->directory('site/branding')
                                            ->maxSize(1024),
                                    ])
                                    ->columns(2),
                                Section::make('Default SEO')
                                    ->schema([
                                        TextInput::make('default_seo_title')
                                            ->maxLength(255),
                                        Textarea::make('default_seo_description')
                                            ->rows(3),
                                        FileUpload::make('default_og_image_path')
                                            ->image()
                                            ->disk('public')
                                            ->directory('site/seo')
                                            ->maxSize(2048),
                                        KeyValue::make('verification_meta')
                                            ->nullable()
                                            ->columnSpanFull(),
                                    ])
                                    ->columns(2),
                            ]),
                        Tab::make('Contact & Footer')
                            ->schema([
                                Section::make('Company Details')
                                    ->schema([
                                        TextInput::make('company_email')
                                            ->email()
                                            ->maxLength(255)
                                            ->nullable(),
                                        TextInput::make('company_phone')
                                            ->maxLength(255)
                                            ->nullable(),
                                        TextInput::make('company_address')
                                            ->maxLength(255)
                                            ->nullable(),
                                        Textarea::make('footer_text')
                                            ->rows(3)
                                            ->columnSpanFull(),
                                    ])
                                    ->columns(2),
                                Section::make('Social Links')
                                    ->schema([
                                        Repeater::make('social_links')
                                            ->schema([
                                                TextInput::make('name')
                                                    ->required(),
                                                TextInput::make('href')
                                                    ->url()
                                                    ->required(),
                                                TextInput::make('icon_key')
                                                    ->required(),
                                                TextInput::make('label')
                                                    ->required(),
                                            ])
                                            ->columnSpanFull(),
                                    ]),
                            ]),
                        Tab::make('Home')
                            ->schema([
                                Section::make('Hero')
                                    ->schema([
                                        TextInput::make('home_hero.badge_text')
                                            ->maxLength(255),
                                        TextInput::make('home_hero.headline')
                                            ->maxLength(255),
                                        TextInput::make('home_hero.headline_emphasis')
                                            ->maxLength(255),
                                        Textarea::make('home_hero.subheadline')
                                            ->rows(3),
                                        TextInput::make('home_hero.primary_cta_label')
                                            ->maxLength(255),
                                        TextInput::make('home_hero.primary_cta_href')
                                            ->maxLength(255),
                                        TextInput::make('home_hero.secondary_cta_label')
                                            ->maxLength(255),
                                        TextInput::make('home_hero.secondary_cta_href')
                                            ->maxLength(255),
                                    ])
                                    ->columns(2),
                                Section::make('Stats')
                                    ->schema([
                                        Repeater::make('home_stats')
                                            ->schema([
                                                TextInput::make('number')
                                                    ->numeric()
                                                    ->required(),
                                                TextInput::make('label')
                                                    ->required(),
                                                TextInput::make('suffix')
                                                    ->maxLength(5),
                                                TextInput::make('decimals')
                                                    ->numeric()
                                                    ->default(0),
                                            ])
                                            ->columnSpanFull(),
                                    ]),
                                Section::make('Technologies')
                                    ->schema([
                                        Repeater::make('home_technologies')
                                            ->schema([
                                                TextInput::make('name')
                                                    ->required(),
                                                TextInput::make('icon_key')
                                                    ->required(),
                                            ])
                                            ->columnSpanFull(),
                                    ]),
                                Section::make('Portfolio Intro')
                                    ->schema([
                                        TextInput::make('home_portfolio_intro.label')
                                            ->maxLength(255),
                                        TextInput::make('home_portfolio_intro.heading')
                                            ->maxLength(255),
                                        Textarea::make('home_portfolio_intro.subheading')
                                            ->rows(3),
                                    ]),
                                Section::make('Services Intro')
                                    ->schema([
                                        TextInput::make('home_services_intro.label')
                                            ->maxLength(255),
                                        TextInput::make('home_services_intro.heading')
                                            ->maxLength(255),
                                        Textarea::make('home_services_intro.subheading')
                                            ->rows(3),
                                    ]),
                                Section::make('Features')
                                    ->schema([
                                        TextInput::make('home_features.label')
                                            ->maxLength(255),
                                        TextInput::make('home_features.heading')
                                            ->maxLength(255),
                                        Textarea::make('home_features.subheading')
                                            ->rows(3),
                                        Repeater::make('home_features.items')
                                            ->schema([
                                                TextInput::make('icon_key')
                                                    ->required(),
                                                TextInput::make('title')
                                                    ->required(),
                                                Textarea::make('description')
                                                    ->rows(3),
                                            ])
                                            ->columnSpanFull(),
                                    ]),
                                Section::make('Testimonials')
                                    ->schema([
                                        TextInput::make('home_testimonials.label')
                                            ->maxLength(255),
                                        TextInput::make('home_testimonials.heading')
                                            ->maxLength(255),
                                        Textarea::make('home_testimonials.subheading')
                                            ->rows(3),
                                        Repeater::make('home_testimonials.items')
                                            ->schema([
                                                TextInput::make('name')
                                                    ->required(),
                                                TextInput::make('company')
                                                    ->required(),
                                                Textarea::make('text')
                                                    ->rows(3),
                                                TextInput::make('rating')
                                                    ->numeric()
                                                    ->default(5),
                                                TextInput::make('avatar_url')
                                                    ->url()
                                                    ->nullable(),
                                            ])
                                            ->columnSpanFull(),
                                    ]),
                                Section::make('FAQs')
                                    ->schema([
                                        TextInput::make('home_faqs.label')
                                            ->maxLength(255),
                                        Textarea::make('home_faqs.subheading')
                                            ->rows(3),
                                        Repeater::make('home_faqs.items')
                                            ->schema([
                                                TextInput::make('question')
                                                    ->required(),
                                                Textarea::make('answer')
                                                    ->rows(3),
                                            ])
                                            ->columnSpanFull(),
                                    ]),
                                Section::make('CTA')
                                    ->schema([
                                        TextInput::make('home_cta.icon_key')
                                            ->maxLength(255),
                                        TextInput::make('home_cta.heading')
                                            ->maxLength(255),
                                        Textarea::make('home_cta.body')
                                            ->rows(3),
                                        TextInput::make('home_cta.primary_cta_label')
                                            ->maxLength(255),
                                        TextInput::make('home_cta.primary_cta_href')
                                            ->maxLength(255),
                                        TextInput::make('home_cta.secondary_cta_label')
                                            ->maxLength(255),
                                        TextInput::make('home_cta.secondary_cta_href')
                                            ->maxLength(255),
                                    ])
                                    ->columns(2),
                            ]),
                        Tab::make('About')
                            ->schema([
                                Section::make('Header')
                                    ->schema([
                                        TextInput::make('about_header.badge_text')
                                            ->maxLength(255),
                                        TextInput::make('about_header.headline')
                                            ->maxLength(255),
                                        Textarea::make('about_header.subheadline')
                                            ->rows(3),
                                    ]),
                                Section::make('Story')
                                    ->schema([
                                        TextInput::make('about_story.heading')
                                            ->maxLength(255),
                                        Repeater::make('about_story.body_paragraphs')
                                            ->schema([
                                                Textarea::make('text')
                                                    ->rows(3),
                                            ])
                                            ->columnSpanFull(),
                                        TextInput::make('about_story.cta_label')
                                            ->maxLength(255),
                                        TextInput::make('about_story.cta_href')
                                            ->maxLength(255),
                                        TextInput::make('about_story.image_url')
                                            ->url()
                                            ->nullable(),
                                        TextInput::make('about_story.image_alt')
                                            ->maxLength(255)
                                            ->nullable(),
                                    ])
                                    ->columns(2),
                                Section::make('Guiding Principles')
                                    ->schema([
                                        TextInput::make('about_principles.section_heading')
                                            ->maxLength(255),
                                        Textarea::make('about_principles.section_subheading')
                                            ->rows(3),
                                        Repeater::make('about_principles.items')
                                            ->schema([
                                                TextInput::make('icon_key')
                                                    ->required(),
                                                TextInput::make('title')
                                                    ->required(),
                                                Textarea::make('description')
                                                    ->rows(3),
                                            ])
                                            ->columnSpanFull(),
                                    ]),
                                Section::make('Mission, Vision, Approach')
                                    ->schema([
                                        Repeater::make('about_cards.items')
                                            ->schema([
                                                TextInput::make('icon_key')
                                                    ->required(),
                                                TextInput::make('title')
                                                    ->required(),
                                                Textarea::make('description')
                                                    ->rows(3),
                                            ])
                                            ->columnSpanFull(),
                                    ]),
                                Section::make('Team')
                                    ->schema([
                                        TextInput::make('about_team.section_heading')
                                            ->maxLength(255),
                                        Textarea::make('about_team.section_subheading')
                                            ->rows(3),
                                        Repeater::make('about_team.members')
                                            ->schema([
                                                TextInput::make('name')
                                                    ->required(),
                                                TextInput::make('role')
                                                    ->required(),
                                                Textarea::make('description')
                                                    ->rows(3),
                                                TextInput::make('image_url')
                                                    ->url()
                                                    ->nullable(),
                                                TextInput::make('image_alt')
                                                    ->maxLength(255)
                                                    ->nullable(),
                                            ])
                                            ->columnSpanFull(),
                                    ]),
                                Section::make('CTA')
                                    ->schema([
                                        TextInput::make('about_cta.icon_key')
                                            ->maxLength(255),
                                        TextInput::make('about_cta.heading')
                                            ->maxLength(255),
                                        Textarea::make('about_cta.body')
                                            ->rows(3),
                                        TextInput::make('about_cta.cta_label')
                                            ->maxLength(255),
                                        TextInput::make('about_cta.cta_href')
                                            ->maxLength(255),
                                    ])
                                    ->columns(2),
                            ]),
                        Tab::make('Pages')
                            ->schema([
                                Section::make('Services Page')
                                    ->schema([
                                        TextInput::make('services_page.header_label')
                                            ->maxLength(255),
                                        TextInput::make('services_page.header_title')
                                            ->maxLength(255),
                                        Textarea::make('services_page.header_subtitle')
                                            ->rows(3),
                                        TextInput::make('services_page.cta_heading')
                                            ->maxLength(255),
                                        Textarea::make('services_page.cta_body')
                                            ->rows(3),
                                        TextInput::make('services_page.cta_button_label')
                                            ->maxLength(255),
                                        TextInput::make('services_page.cta_button_href')
                                            ->maxLength(255),
                                    ])
                                    ->columns(2),
                                Section::make('Portfolio Page')
                                    ->schema([
                                        TextInput::make('portfolio_page.header_label')
                                            ->maxLength(255),
                                        TextInput::make('portfolio_page.header_title')
                                            ->maxLength(255),
                                        Textarea::make('portfolio_page.header_subtitle')
                                            ->rows(3),
                                        TextInput::make('portfolio_page.cta_heading')
                                            ->maxLength(255),
                                        Textarea::make('portfolio_page.cta_body')
                                            ->rows(3),
                                        TextInput::make('portfolio_page.cta_button_label')
                                            ->maxLength(255),
                                        TextInput::make('portfolio_page.cta_button_href')
                                            ->maxLength(255),
                                    ])
                                    ->columns(2),
                                Section::make('Products Page')
                                    ->schema([
                                        TextInput::make('products_page.header_label')
                                            ->maxLength(255),
                                        TextInput::make('products_page.header_title')
                                            ->maxLength(255),
                                        Textarea::make('products_page.header_subtitle')
                                            ->rows(3),
                                    ])
                                    ->columns(2),
                                Section::make('Blog Page')
                                    ->schema([
                                        TextInput::make('blog_page.header_label')
                                            ->maxLength(255),
                                        TextInput::make('blog_page.header_title')
                                            ->maxLength(255),
                                        Textarea::make('blog_page.header_subtitle')
                                            ->rows(3),
                                    ])
                                    ->columns(2),
                            ]),
                        Tab::make('Contact Page')
                            ->schema([
                                Section::make('Header')
                                    ->schema([
                                        TextInput::make('contact_header.badge_text')
                                            ->maxLength(255),
                                        TextInput::make('contact_header.headline')
                                            ->maxLength(255),
                                        Textarea::make('contact_header.subheadline')
                                            ->rows(3),
                                    ])
                                    ->columns(2),
                                Section::make('Contact Details')
                                    ->schema([
                                        Repeater::make('contact_details')
                                            ->schema([
                                                TextInput::make('icon_key')
                                                    ->required(),
                                                TextInput::make('title')
                                                    ->required(),
                                                TextInput::make('content')
                                                    ->required(),
                                                TextInput::make('href')
                                                    ->maxLength(255)
                                                    ->nullable(),
                                                TextInput::make('aria_label')
                                                    ->maxLength(255)
                                                    ->nullable(),
                                            ])
                                            ->columnSpanFull(),
                                    ]),
                                Section::make('Social')
                                    ->schema([
                                        TextInput::make('contact_social.heading')
                                            ->maxLength(255),
                                        Textarea::make('contact_social.subheading')
                                            ->rows(3),
                                        Repeater::make('contact_social.links')
                                            ->schema([
                                                TextInput::make('name')
                                                    ->required(),
                                                TextInput::make('href')
                                                    ->url()
                                                    ->required(),
                                                TextInput::make('icon_key')
                                                    ->required(),
                                                TextInput::make('label')
                                                    ->required(),
                                            ])
                                            ->columnSpanFull(),
                                    ])
                                    ->columns(2),
                            ]),
                    ]),
            ]);
    }
}
