<?php

namespace App\Http\Requests\Admin;

use Illuminate\Foundation\Http\FormRequest;

class UpdateSiteSettingRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'site_name' => ['required', 'string', 'max:255'],
            'tagline' => ['nullable', 'string', 'max:255'],
            'company_email' => ['nullable', 'email', 'max:255'],
            'company_phone' => ['nullable', 'string', 'max:255'],
            'company_address' => ['nullable', 'string', 'max:255'],
            'footer_text' => ['nullable', 'string'],
            'social_links' => ['nullable', 'array'],
            'social_links.*.name' => ['required', 'string', 'max:255'],
            'social_links.*.href' => ['required', 'url', 'max:255'],
            'social_links.*.icon_key' => ['required', 'string', 'max:255'],
            'social_links.*.label' => ['required', 'string', 'max:255'],
            'default_seo_title' => ['nullable', 'string', 'max:255'],
            'default_seo_description' => ['nullable', 'string'],
            'verification_meta' => ['nullable', 'array'],
            'logo' => ['nullable', 'image', 'max:2048'],
            'favicon' => ['nullable', 'image', 'max:1024'],
            'default_og_image' => ['nullable', 'image', 'max:2048'],
            'remove_logo' => ['nullable', 'boolean'],
            'remove_favicon' => ['nullable', 'boolean'],
            'remove_default_og_image' => ['nullable', 'boolean'],
            'home_hero' => ['nullable', 'array'],
            'home_hero.badge_text' => ['nullable', 'string', 'max:255'],
            'home_hero.headline' => ['nullable', 'string', 'max:255'],
            'home_hero.headline_emphasis' => ['nullable', 'string', 'max:255'],
            'home_hero.subheadline' => ['nullable', 'string'],
            'home_hero.primary_cta_label' => ['nullable', 'string', 'max:255'],
            'home_hero.primary_cta_href' => ['nullable', 'string', 'max:255'],
            'home_hero.secondary_cta_label' => ['nullable', 'string', 'max:255'],
            'home_hero.secondary_cta_href' => ['nullable', 'string', 'max:255'],
            'home_stats' => ['nullable', 'array'],
            'home_stats.*.number' => ['nullable', 'numeric'],
            'home_stats.*.label' => ['nullable', 'string', 'max:255'],
            'home_stats.*.suffix' => ['nullable', 'string', 'max:10'],
            'home_stats.*.decimals' => ['nullable', 'integer'],
            'home_technologies' => ['nullable', 'array'],
            'home_technologies.*.name' => ['nullable', 'string', 'max:255'],
            'home_technologies.*.icon_key' => ['nullable', 'string', 'max:255'],
            'home_portfolio_intro' => ['nullable', 'array'],
            'home_portfolio_intro.label' => ['nullable', 'string', 'max:255'],
            'home_portfolio_intro.heading' => ['nullable', 'string', 'max:255'],
            'home_portfolio_intro.subheading' => ['nullable', 'string'],
            'home_services_intro' => ['nullable', 'array'],
            'home_services_intro.label' => ['nullable', 'string', 'max:255'],
            'home_services_intro.heading' => ['nullable', 'string', 'max:255'],
            'home_services_intro.subheading' => ['nullable', 'string'],
            'home_features' => ['nullable', 'array'],
            'home_features.label' => ['nullable', 'string', 'max:255'],
            'home_features.heading' => ['nullable', 'string', 'max:255'],
            'home_features.subheading' => ['nullable', 'string'],
            'home_features.items' => ['nullable', 'array'],
            'home_features.items.*.icon_key' => ['nullable', 'string', 'max:255'],
            'home_features.items.*.title' => ['nullable', 'string', 'max:255'],
            'home_features.items.*.description' => ['nullable', 'string'],
            'home_testimonials' => ['nullable', 'array'],
            'home_testimonials.label' => ['nullable', 'string', 'max:255'],
            'home_testimonials.heading' => ['nullable', 'string', 'max:255'],
            'home_testimonials.subheading' => ['nullable', 'string'],
            'home_testimonials.items' => ['nullable', 'array'],
            'home_testimonials.items.*.name' => ['nullable', 'string', 'max:255'],
            'home_testimonials.items.*.company' => ['nullable', 'string', 'max:255'],
            'home_testimonials.items.*.text' => ['nullable', 'string'],
            'home_testimonials.items.*.rating' => ['nullable', 'integer'],
            'home_testimonials.items.*.avatar_url' => ['nullable', 'url', 'max:255'],
            'home_faqs' => ['nullable', 'array'],
            'home_faqs.label' => ['nullable', 'string', 'max:255'],
            'home_faqs.subheading' => ['nullable', 'string'],
            'home_faqs.items' => ['nullable', 'array'],
            'home_faqs.items.*.question' => ['nullable', 'string', 'max:255'],
            'home_faqs.items.*.answer' => ['nullable', 'string'],
            'home_cta' => ['nullable', 'array'],
            'home_cta.icon_key' => ['nullable', 'string', 'max:255'],
            'home_cta.heading' => ['nullable', 'string', 'max:255'],
            'home_cta.body' => ['nullable', 'string'],
            'home_cta.primary_cta_label' => ['nullable', 'string', 'max:255'],
            'home_cta.primary_cta_href' => ['nullable', 'string', 'max:255'],
            'home_cta.secondary_cta_label' => ['nullable', 'string', 'max:255'],
            'home_cta.secondary_cta_href' => ['nullable', 'string', 'max:255'],
            'about_header' => ['nullable', 'array'],
            'about_header.badge_text' => ['nullable', 'string', 'max:255'],
            'about_header.headline' => ['nullable', 'string', 'max:255'],
            'about_header.subheadline' => ['nullable', 'string'],
            'about_story' => ['nullable', 'array'],
            'about_story.heading' => ['nullable', 'string', 'max:255'],
            'about_story.body_paragraphs' => ['nullable', 'array'],
            'about_story.body_paragraphs.*' => ['nullable', 'string'],
            'about_story.cta_label' => ['nullable', 'string', 'max:255'],
            'about_story.cta_href' => ['nullable', 'string', 'max:255'],
            'about_story.image_url' => ['nullable', 'string', 'max:255'],
            'about_story.image_alt' => ['nullable', 'string', 'max:255'],
            'about_principles' => ['nullable', 'array'],
            'about_principles.section_heading' => ['nullable', 'string', 'max:255'],
            'about_principles.section_subheading' => ['nullable', 'string'],
            'about_principles.items' => ['nullable', 'array'],
            'about_principles.items.*.icon_key' => ['nullable', 'string', 'max:255'],
            'about_principles.items.*.title' => ['nullable', 'string', 'max:255'],
            'about_principles.items.*.description' => ['nullable', 'string'],
            'about_cards' => ['nullable', 'array'],
            'about_cards.items' => ['nullable', 'array'],
            'about_cards.items.*.icon_key' => ['nullable', 'string', 'max:255'],
            'about_cards.items.*.title' => ['nullable', 'string', 'max:255'],
            'about_cards.items.*.description' => ['nullable', 'string'],
            'about_team' => ['nullable', 'array'],
            'about_team.section_heading' => ['nullable', 'string', 'max:255'],
            'about_team.section_subheading' => ['nullable', 'string'],
            'about_team.members' => ['nullable', 'array'],
            'about_team.members.*.name' => ['nullable', 'string', 'max:255'],
            'about_team.members.*.role' => ['nullable', 'string', 'max:255'],
            'about_team.members.*.description' => ['nullable', 'string'],
            'about_team.members.*.image_url' => ['nullable', 'string', 'max:255'],
            'about_team.members.*.image_alt' => ['nullable', 'string', 'max:255'],
            'about_cta' => ['nullable', 'array'],
            'about_cta.icon_key' => ['nullable', 'string', 'max:255'],
            'about_cta.heading' => ['nullable', 'string', 'max:255'],
            'about_cta.body' => ['nullable', 'string'],
            'about_cta.cta_label' => ['nullable', 'string', 'max:255'],
            'about_cta.cta_href' => ['nullable', 'string', 'max:255'],
            'services_page' => ['nullable', 'array'],
            'services_page.header_label' => ['nullable', 'string', 'max:255'],
            'services_page.header_title' => ['nullable', 'string', 'max:255'],
            'services_page.header_subtitle' => ['nullable', 'string'],
            'services_page.cta_heading' => ['nullable', 'string', 'max:255'],
            'services_page.cta_body' => ['nullable', 'string'],
            'services_page.cta_button_label' => ['nullable', 'string', 'max:255'],
            'services_page.cta_button_href' => ['nullable', 'string', 'max:255'],
            'portfolio_page' => ['nullable', 'array'],
            'portfolio_page.header_label' => ['nullable', 'string', 'max:255'],
            'portfolio_page.header_title' => ['nullable', 'string', 'max:255'],
            'portfolio_page.header_subtitle' => ['nullable', 'string'],
            'portfolio_page.cta_heading' => ['nullable', 'string', 'max:255'],
            'portfolio_page.cta_body' => ['nullable', 'string'],
            'portfolio_page.cta_button_label' => ['nullable', 'string', 'max:255'],
            'portfolio_page.cta_button_href' => ['nullable', 'string', 'max:255'],
            'products_page' => ['nullable', 'array'],
            'products_page.header_label' => ['nullable', 'string', 'max:255'],
            'products_page.header_title' => ['nullable', 'string', 'max:255'],
            'products_page.header_subtitle' => ['nullable', 'string'],
            'blog_page' => ['nullable', 'array'],
            'blog_page.header_label' => ['nullable', 'string', 'max:255'],
            'blog_page.header_title' => ['nullable', 'string', 'max:255'],
            'blog_page.header_subtitle' => ['nullable', 'string'],
            'contact_header' => ['nullable', 'array'],
            'contact_header.badge_text' => ['nullable', 'string', 'max:255'],
            'contact_header.headline' => ['nullable', 'string', 'max:255'],
            'contact_header.subheadline' => ['nullable', 'string'],
            'contact_details' => ['nullable', 'array'],
            'contact_details.*.icon_key' => ['nullable', 'string', 'max:255'],
            'contact_details.*.title' => ['nullable', 'string', 'max:255'],
            'contact_details.*.content' => ['nullable', 'string'],
            'contact_details.*.href' => ['nullable', 'string', 'max:255'],
            'contact_details.*.aria_label' => ['nullable', 'string', 'max:255'],
            'contact_social' => ['nullable', 'array'],
            'contact_social.heading' => ['nullable', 'string', 'max:255'],
            'contact_social.subheading' => ['nullable', 'string'],
            'contact_social.links' => ['nullable', 'array'],
            'contact_social.links.*.name' => ['nullable', 'string', 'max:255'],
            'contact_social.links.*.href' => ['nullable', 'string', 'max:255'],
            'contact_social.links.*.icon_key' => ['nullable', 'string', 'max:255'],
            'contact_social.links.*.label' => ['nullable', 'string', 'max:255'],
        ];
    }

    public function messages(): array
    {
        return [
            'site_name.required' => 'The site name is required.',
            'company_email.email' => 'Enter a valid company email address.',
            'social_links.*.href.url' => 'Social links must include a valid URL.',
            'logo.image' => 'The logo must be a valid image file.',
            'favicon.image' => 'The favicon must be a valid image file.',
            'default_og_image.image' => 'The default SEO image must be a valid image file.',
        ];
    }
}
